Repository tnghgks/wouldUmarket, pull requests merged in 2022-12, with the labels that each got.

#19 Feat: 홈포스트 컴포넌트 생성
  src/App.js
  src/Components/HomePost.jsx
Labels: feat

#20 Feat: 홈포스트 컴포넌트 생성
  src/Components/homepost/HomePost.jsx
  src/Components/homepost/HomePostOnlytext.jsx
Labels: feat

#47 feat: button 컴포넌트 생성
  src/Components/button/CommonButton.jsx
Labels: feat

#50 feat: SetProfile 페이지 컴포넌트 생성
  src/Pages/SetProfile/SetProfile.jsx
Labels: feat

#60 Feat: Home 컴포넌트 생성
  src/Pages/Home/EmptyFeed/EmptyFeed.jsx
  src/Pages/Home/FollowingFeed/FollowingFeed.jsx
Labels: feat

#79 Feat: ChatListProfeile컴퍼넌트생성
  src/Components/ChatlistProfile.jsx
Labels: feat

#80 Feat: ChatLsit컴포넌트생성
  src/Pages/Chat/ChatList/ChatList.jsx
Labels: feat

#83 design: Register 디자인 수정
  src/Pages/Register/Register.jsx
Labels: design

#84 feat: NotFound404pages 컴포넌트 생성
  src/Pages/Page404/Page404.jsx
Labels: feat

#86 feat: ChatRoom 컨포넌트 생성
  src/Pages/Chat/ChatRoom/ChatRoom.jsx
Labels: feat

#90 remove: Button Components 삭제
  src/Components/button/LargeButton.jsx
  src/Components/button/LargeDisableButton.jsx
  src/Components/button/MediumActivButton.jsx
  src/Components/button/MediumButton.jsx
  src/Components/button/MediumDisableButton.jsx
  src/Components/button/MediumSmallButton.jsx
  src/Components/button/MediumSmallDisableBtn.jsx
  src/Components/button/SmallActivButton.jsx
  src/Components/button/SmallButton.jsx
Labels: remove

#98 design: CommonButton CSS 수정
  src/Components/button/CommonButton.jsx
Labels: design

#101 Design: 세부 컴포넌트 CSS 수정
  src/Components/Comment.jsx
  src/Components/CommonAlert.jsx
  src/Components/CommonInput.jsx
  src/Components/TextActivInput.jsx
  src/Components/UserFollow.jsx
  src/Components/UserSerch.jsx
Labels: design

#106 design: ChatListProflie CSS 수정
  src/Components/ChatlistProfile.jsx
Labels: design

#108 feat: 로그인 Input 데이터 저장 구현
  src/Pages/Login/LoginEmail.jsx
Labels: feat

#112 feat: Search 컴포넌트 검색 기능 구현
  src/Components/Navbar/SearchNav.jsx
  src/Components/UserSearch.jsx
  src/Pages/Search/Search.jsx
Labels: feat

#114 design: Commoninput마크업수정
  src/Components/CommonInput.jsx
Labels: design

#115 feat: ChatRoomChat 컴퍼넌트 생성
  src/Components/ChatRoomChat.jsx
Labels: feat

#117 Design: Chat컴포넌트수정
  src/Components/ChatRoomChat.jsx
  src/Pages/Chat/ChatList/ChatList.jsx
  src/Pages/Chat/ChatRoom/ChatRoom.jsx
Labels: design

#119 feat: PostDetail 데이터요청 및 데이터랜더링
  src/Components/Modal.jsx
  src/Components/icon/IconMoreVerticalSmall.jsx
  src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/Router/Router.jsx
Labels: feat

#122 feat: Store에 UserInfo Reducer 추가
  src/Components/CommonInput.jsx
  src/Pages/Login/LoginEmail.jsx
  src/store/UserInfo.js
  src/store/index.js
Labels: feat

#129 feat: Splash애니메이션추가
  src/Pages/SplashScreen/SplashLoader/SplashLoader.jsx
  src/Pages/SplashScreen/SplashScreen.jsx
  src/assets/spaceship.svg
  src/assets/spaceship_shadow.svg
Labels: feat

#131 design: CommonButton 컴포넌트 이벤트프롭스 설정
  src/Components/button/CommonButton.jsx
Labels: design

#133 feat: UserInfo follow,unfollow 기능 추가
  src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
  src/Router/Router.jsx
Labels: feat

#135 feat: UserProducts fetch data 및 랜더링
  src/Components/Product.jsx
  src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx
Labels: feat

#137 feat: Chatlist 컴퍼넌트 Link 기능 추가, 마크업 ul 추가
  src/Pages/Chat/ChatList/ChatList.jsx
Labels: feat, design

#139 Design: NavBar,ChatListProfile, ChatList컴포넌트수정
  src/Components/ChatlistProfile.jsx
  src/Components/Navbar/BasicNav.jsx
  src/Components/Navbar/ChatNav.jsx
  src/Components/Navbar/MainNav.jsx
  src/Components/Navbar/SearchNav.jsx
  src/Components/Navbar/UploadNav.jsx
  src/Pages/Chat/ChatList/ChatList.jsx
Labels: design

#142 feat: profileReducer 생성 및 userInfo state 변경
  package-lock.json
  package.json
  src/store/Profile.js
  src/store/UserInfo.js
  src/store/index.js
Labels: feat

#144 feat: react-cookie 설정 및 setter, getter 함수 설정
  src/cookie/index.js
Labels: feat

#147 feat: Profile 컴포넌트에 react-cookie 적용 및 Redux 적용
  src/Components/TabMenu.jsx
  src/Components/UserSearch.jsx
  src/Pages/Login/LoginEmail.jsx
  src/Pages/Profile/UserProfile/Profile.jsx
  src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
  src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
  src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx
  src/Pages/Search/Search.jsx
Labels: feat

#153 feat: UserInfo컴포넌트 버튼 권한별 출력
  src/Pages/Profile/UserProfile/EditBtns/EditBtns.jsx
  src/Pages/Profile/UserProfile/FollowBtns/FollowBtns.jsx
  src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
  src/Router/Router.jsx
Labels: feat

#154 feat: home post컴포넌트화
  src/Components/HomePost.jsx
Labels: feat

#166 feat: Refresh시 UserInfo 불러오기 기능 추가
  src/App.js
  src/Components/Auth/Authentication.jsx
  src/Components/icon/IconUser.jsx
Labels: feat

#168 feat: HeartIcon Toggle 기능 추가
  src/Components/HomePost.jsx
  src/Components/icon/IconHeart.jsx
  src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
  src/assets/icon/icon-heart-active.png
  src/assets/icon/icon-heart-active.svg
Labels: feat

#175 feat: LoginEmail 기능 개선
  src/Pages/Login/LoginEmail.jsx
Labels: feat

#179 design: CommonButton 컴퍼넌트 disabled 속성 적용
  src/Components/button/CommonButton.jsx
Labels: design

#182 feat: SetProfile 기능구현
  src/Pages/SetProfile/SetProfile.jsx
  src/store/Register.js
Labels: feat

#184 feat: PostDetail Store사용 및 기능 개선
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/store/PostDetail.js
  src/store/index.js
Labels: feat

#185 feat: SearchData Store에 검색데이터 캐싱 및 fetch 코드 분리
  src/Pages/Search/Search.jsx
  src/store/SearchData.js
  src/store/index.js
Labels: feat

#188 feat: Feed기능구현
  src/Pages/Home/EmptyFeed/EmptyFeed.jsx
  src/Pages/Home/FollowingFeed/FollowingFeed.jsx
  src/Pages/Home/Home.jsx
Labels: feat, remove

#190 feat: Register 버튼비활성화구현
  src/Pages/Home/Home.jsx
  src/Pages/Register/Register.jsx
Labels: feat, style

#192 feat: Modal Store 생성 및 Modal 기능 추가
  src/Components/DeleteAlert.jsx
  src/Components/HomePost.jsx
  src/Components/Modal.jsx
  src/Components/Navbar/BasicNav.jsx
  src/Components/icon/IconMoreVertical.jsx
  src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/Pages/Profile/UserProfile/Profile.jsx
  src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
  src/store/Modal.js
  src/store/index.js
Labels: feat

#197 feat: Search 컴포넌트 기능 추가
  src/Components/UserSearch.jsx
  src/Pages/Profile/UserProfile/FollowBtns/FollowBtns.jsx
  src/Pages/Search/Search.jsx
  src/store/SearchData.js
Labels: feat

#199 feat: Follow,Following page 라우팅 및 기능추가
  src/Components/UserFollow.jsx
  src/Components/button/CommonButton.jsx
  src/Pages/Profile/Follower/Followers.jsx
  src/Pages/Profile/Follows/Follows.jsx
  src/Pages/Profile/UserProfile/Profile.jsx
  src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
  src/Router/Router.jsx
  src/assets/Ellipse 6.png
  src/assets/Ellipse-1.png
  src/assets/basic-profile-img.png
  src/store/Follow.js
  src/store/Profile.js
  src/store/index.js
Labels: feat

#201 feat: Follows Page 중복되는 코드 병합 및 페이징기능추가
  src/Components/Navbar/MainNav.jsx
  src/Pages/Profile/Follows/Follows.jsx
  src/store/Follow.js
Labels: feat

#205 design: Basic Profile 컴포넌트 테두리 0.5px 추가
  src/Components/BasicProfileImg.jsx
  src/Components/SmallBasicProfile.jsx
Labels: design

#206 feat: Post 댓글 기능 추가
  src/Components/Comment.jsx
  src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/store/PostDetail.js
Labels: feat

#208 feat: Modal 권한별 다른 Modal 보여주기
  src/Components/HomePost.jsx
  src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
Labels: feat

#210 Feat: EditUserProfile기능
  src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx
  src/store/Profile.js
Labels: feat

#212 Feat: EditUserProfile 유저 설정 값 가져오기
  src/Components/CommonInput.jsx
  src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx
Labels: feat

#216 Feat: EditUserProfile page disabled기능
  src/Components/Navbar/UploadNav.jsx
  src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx
Labels: feat

#218 feat: Loader 컴포넌트 생성 및 Search에 적용
  src/Components/Loader.jsx
  src/Pages/Search/Search.jsx
  src/assets/loader_bg.png
  src/assets/loader_human.png
  src/assets/loader_planet.png
Labels: feat

#220 feat: HomePost 하트 토글 및 하트 기능 추가
  src/Components/HomePost.jsx
  src/Pages/Home/EmptyFeed/EmptyFeed.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/store/PostDetail.js
Labels: feat, style

#223 feat: 회원가입 API 전송 기능
  src/Pages/Register/Register.jsx
  src/Pages/SetProfile/SetProfile.jsx
Labels: feat, style

#224 fix: 자잘한 버그 수정
  src/Components/Auth/Authentication.jsx
  src/Components/Comment.jsx
  src/Components/Loader.jsx
  src/Components/Navbar/ChatNav.jsx
  src/Components/Navbar/SearchNav.jsx
  src/Components/UserSearch.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
  src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx
  src/Pages/Profile/Follows/Follows.jsx
  src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
  src/Pages/Search/Search.jsx
  src/store/Profile.js
  src/store/UserInfo.js
Labels: feat

#230 feat: SetProfile 프로필 이미지 업로드 기능
  src/Pages/SetProfile/SetProfile.jsx
Labels: feat, style

#231 feat: Home Post 기능추가
  src/App.js
  src/Components/HomePost.jsx
  src/Pages/Home/EmptyFeed/EmptyFeed.jsx
  src/Pages/Post/PostDetail/PostDetail.jsx
Labels: feat

#235 feat: User Profile 기능 추가 및 버그 수정
  src/Components/HomePost.jsx
  src/Pages/Home/EmptyFeed/EmptyFeed.jsx
  src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
  src/store/PostList.js
  src/store/index.js
Labels: feat, fix

#238 fix: UserProfile Intro 누락 해결
  src/Pages/SetProfile/SetProfile.jsx
  src/store/Profile.js
Labels: fix

#245 Feat: EditProduct 기능 구현
  src/Pages/Profile/Product/AddProduct.jsx
  src/Pages/Profile/Product/EditProduct/Editproduct.jsx
  src/Pages/Profile/UserProfile/EditBtns/EditBtns.jsx
  src/Router/Router.jsx
  src/store/Product.js
Labels: feat

#247 feat: Product Modal 기능 추가
  src/Components/Navbar/BasicNav.jsx
  src/Components/Product.jsx
  src/Pages/Login/LoginEmail.jsx
  src/Pages/Profile/UserProfile/Profile.jsx
  src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx
  src/store/Auth.js
  src/store/ProductList.js
  src/store/index.js
Labels: feat

#249 feat: Comment 및 Follow 페이지 프로필 사진 클릭 시 이동 기능 추가
  src/Components/UserFollow.jsx
  src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
Labels: feat

#252 feat: 자동로그인처리
  src/Pages/Profile/UserProfile/Profile.jsx
  src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
  src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx
  src/Pages/SplashScreen/SplashScreen.jsx
Labels: feat, fix

#253 Design: 컴포넌트별 디자인 수정
  src/Components/Navbar/BasicNav.jsx
  src/Pages/Page404/Page404.jsx
  src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
  src/Pages/Search/Search.jsx
  src/assets/notFound404.png
  src/store/SearchData.js
Labels: feat, design

#255 Fix: Product detail 수정
  src/Pages/Profile/Product/AddProduct.jsx
  src/Pages/Profile/Product/EditProduct/Editproduct.jsx
  src/store/Product.js
Labels: fix

#256 Design: 컴포넌트별 디자인 수정
  src/Components/Loader.jsx
  src/Components/Product.jsx
  src/Pages/Home/EmptyFeed/EmptyFeed.jsx
  src/Pages/Profile/Product/AddProduct.jsx
  src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
  src/assets/UploadImage.png
Labels: feat, design

#258 style: SetProfile 기능 스타일 수정
  src/Pages/SetProfile/SetProfile.jsx
Labels: style
