Repository tnghgks/wouldUmarket, pull requests merged in 2023-01, with the labels that each got.

#263 Feat/edit product리팩토링
  src/Pages/Profile/Product/EditProduct/EditProductInput/EditProductInput.jsx
  src/Pages/Profile/Product/EditProduct/Editproduct.jsx
  src/Pages/Profile/Product/EditProduct/ProductImg/ProductImg.jsx
  src/store/Product.js
Labels: feat

#277 feat: SetProfile 버튼 활성화 기능 수정
  src/Pages/SetProfile/SetProfile.jsx
Labels: feat

#279 feat: Search 페이지 기능 개선
  src/Components/NotFoundResult.jsx
  src/Components/UserSearch.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Search/Search.jsx
  src/assets/NotFoundResult.png
Labels: feat

#283 style: CommonButton 글자 위치 수정
  src/Components/button/CommonButton.jsx
Labels: style

#285 fix: EditUserProfile 유효성 검사 수정
  src/Pages/EditUserProfile/EditUserProfile.jsx
Labels: fix

#287 Fix: EditProduct수정
  src/Pages/AddProduct/AddProduct.jsx
  src/Pages/EditProduct/EditProductInput/EditProductInput.jsx
  src/Pages/EditProduct/Editproduct.jsx
  src/Pages/EditProduct/ProductImg/ProductImg.jsx
  src/Pages/EditUserProfile/EditUserProfile.jsx
  src/store/Product.js
Labels: fix

#289 style: ChatListProfileImg 수정
  src/Components/Chat/ChatListProfile.jsx
Labels: style

#291 Style: ChatRoom수정
  src/Components/Chat/ChatRoomChat.jsx
  src/Components/Comment.jsx
  src/Pages/Chat/ChatRoom/ChatRoom.jsx
Labels: style

#293 style: Enabled 시, 변경되는 Button 색상 수정
  src/Pages/AddProduct/AddProduct.jsx
  src/Pages/EditUserProfile/EditUserProfile.jsx
Labels: style

#295 fix: Auth관련 에러 수정
  src/Components/Auth/Authentication.jsx
  src/Pages/Login/Login.jsx
  src/Pages/SplashScreen/SplashScreen.jsx
Labels: fix

#299 feat: API 인스턴스생성
  src/api/api.js
Labels: feat

#306 refactor: PostUpload.jsx 외 10개 파일 axios 마이그레이션
  package-lock.json
  package.json
  src/Components/Product.jsx
  src/Pages/AddProduct/AddProduct.jsx
  src/Pages/EditProduct/Editproduct.jsx
  src/Pages/EditUserProfile/EditUserProfile.jsx
  src/Pages/PostDetail/CommentItem/CommentItem.jsx
  src/Pages/PostUpload/PostUpload.jsx
  src/Pages/Register/Register.jsx
  src/Pages/UserProfile/Profile.jsx
  src/Pages/UserProfile/UserInfo/UserInfo.jsx
  src/api/auth.js
  src/api/post.js
  src/api/product.js
  src/api/profile.js
  src/store/Product.js
  src/store/ProductList.js
  src/store/Profile.js
Labels: feat, refactoring

#309 refactor: React Hook Form 마이그레이션 (LoginEmail, EditUserProfile)
  package-lock.json
  package.json
  src/Components/Input/CommonInput.jsx
  src/Pages/EditUserProfile/EditUserProfile.jsx
  src/Pages/LoginEmail/LoginEmail.jsx
  src/api/auth.js
  src/api/profile.js
  src/constant/regex.js
Labels: refactoring

#312 feat: constant/regex 오타 수정
  src/constant/regex.js
Labels: fix

#313 refactor: React Hook Form 마이그레이션 (Register, SetProfile)
  package-lock.json
  package.json
  src/Pages/Register/Register.jsx
  src/Pages/SetProfile/SetProfile.jsx
  src/api/setprofile.js
  src/constant/regex.js
Labels: feat, refactoring

#316 feat: 접근성 향상을 위한 @axe-core/react 설치
  package-lock.json
  package.json
  src/index.js
  src/util/axeTester.js
Labels: feat

#318 chore: Commoninput 수정
  src/Components/Input/CommonInput.jsx
Labels: refactoring
