Repository tnghgks/wouldUmarket, pull requests merged in 2023-02, with the labels that each got.

#325 refactor: 시멘틱 마크업
  src/Components/ImageSlider.jsx
  src/Components/Product.jsx
  src/Components/TabMenu.jsx
  src/Components/UserSearch.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Search/Search.jsx
  src/Pages/UserProfile/Profile.jsx
  src/Pages/UserProfile/UserInfo/UserInfo.jsx
  src/Pages/UserProfile/UserPost/UserPost.jsx
  src/Pages/UserProfile/UserProducts/UserProducts.jsx
Labels: refactoring

#322 Refactor/react hook form 마이그레이션
  src/Pages/AddProduct/AddProduct.jsx
  src/Pages/EditProduct/Editproduct.jsx
  src/constant/regex.js
  src/util/priceComma.js
Labels: refactoring

#327 refactor: 시맨틱마크업
  src/Components/Comment.jsx
  src/Components/HomePost.jsx
  src/Components/ImageSlider.jsx
  src/Components/Navbar/UploadNav.jsx
  src/Pages/AddProduct/AddProduct.jsx
  src/Pages/EditProduct/Editproduct.jsx
  src/Pages/EditUserProfile/EditUserProfile.jsx
  src/Pages/LoginEmail/LoginEmail.jsx
  src/Pages/PostDetail/CommentItem/CommentItem.jsx
  src/Pages/PostDetail/PostDetail.jsx
Labels: refactoring

#329 refactor: 시맨틱 마크업
  src/Pages/PostUpload/PostUpload.jsx
  src/Pages/SplashScreen/SplashScreen.jsx
Labels: refactoring

#332 refactor: 시멘틱 마크업
  src/Components/ImageComponents/BasicProfileImg.jsx
  src/Components/UserFollow.jsx
  src/Pages/Follows/Follows.jsx
Labels: refactoring

#334 feat: 무한스크롤 커스텀 훅 생성 및 적용
  src/Hooks/useInfinityScroll.jsx
  src/Pages/Home/Feed.jsx
  src/Pages/UserProfile/Profile.jsx
  src/Pages/UserProfile/UserPost/UserPost.jsx
  src/store/PostList.js
  src/store/SearchData.js
Labels: feat, refactoring

#336 feat: useDebounce 커스텀 훅 생성 및 적용
  src/Components/UserSearch.jsx
  src/Hooks/useDebounce.jsx
  src/Pages/Search/RecentList/RecentList.jsx
  src/Pages/Search/Search.jsx
  src/Pages/Search/SearchResult/SearchResult.jsx
Labels: feat, refactoring

#338 feat: 페이지별 loader 추가
  src/Components/Loader.jsx
  src/Pages/Home/Feed.jsx
  src/Pages/PostDetail/PostDetail.jsx
  src/Pages/UserProfile/Profile.jsx
  src/Pages/UserProfile/UserInfo/UserInfo.jsx
  src/Pages/UserProfile/UserPost/UserPost.jsx
  src/store/PostDetail.js
  src/store/PostList.js
  src/store/Profile.js
Labels: feat

#340 fix: 무한 로딩 버그수정 및 로그인 버그수정
  src/Components/Navbar/BasicNav.jsx
  src/Pages/Home/Feed.jsx
  src/store/UserInfo.js
Labels: fix

#344 refactor: 이미지 슬라이더 디자인 변경
  src/Components/ImageSlider.jsx
  src/assets/icon/left-arrow-icon.png
  src/assets/icon/right-arrow-icon.png
Labels: design, style, refactoring

#346 fix: 배포 오류 수정 (정규표현식 eslint-disable-next-line 위치 수정)
  src/constant/regex.js
Labels: fix
